#!/usr/bin/env zsh
emulate -R zsh
setopt nounset
module_path=("$1")
typeset control_fd=$2 report_fd=$3 command=''
zmodload zdraw || exit 1

report() { print -r -u "$report_fd" -- "$*"; }
barrier() { read -r -u "$control_fd" command || exit 1; }
check() { "$@" || { report "FAIL $*"; exit 1; }; }

typeset -a dimensions=(sentinel) position cells
typeset -a compiled_features=("${zdraw_features[@]}")
check_features() {
  [[ "${(j: :)zdraw_features}" == "${(j: :)compiled_features}" ]] || exit 1
}
check zmodload -F -e zdraw +p:zdraw_features
check_features
check zdraw geometry dimensions
report "before ${(j: :)dimensions}"
barrier

check zdraw init
{
  check zdraw addwin sample 4 20 1 1
  check zdraw attr sample bold green/black
  check zdraw string sample hello
  check zdraw move sample 0 0
  check zdraw querychar sample cells
  [[ $cells[1] == h && $cells[2] == green/black && $cells[3] == bold ]] || exit 1
  check zdraw refresh sample stdscr
  check zdraw position stdscr position
  # Discovery is stable after initialization and agrees with the legacy probes.
  check_features
  zdraw mouse
  [[ $? -eq $(( ! ${zdraw_features[(Ie)mouse]} )) ]] || exit 1
  zdraw resize 0 0
  [[ $? -eq $(( ${zdraw_features[(Ie)resize]} ? 0 : 2 )) ]] || exit 1
  report "ready $position[5] $position[6]"
  barrier

  # Leave a drawing change pending: discovery must not present it.
  check zdraw string sample pending
  check zdraw border sample '|' '|' '-' '-' '+' '+' '+' '+'
  check zdraw spans sample 1 1 bold batch '' ed
  check zdraw spansclip sample 2 1 4 bold pending '' trailing
  typeset -A text_info
  check zdraw textinfo text_info abcdef 3
  [[ $text_info[text] == abc && $text_info[width] == 3 ]] || exit 1
  typeset -A runtime_colors
  check zdraw colorinfo runtime_colors
  check zdraw truecolor off
  if [[ $runtime_colors[truecolor_supported] == 1 ]]; then
    check zdraw truecolor on
    check zdraw spans sample 1 1 '#123456/#234567' RGB
    check zdraw truecolor off
  else
    zdraw truecolor on
    [[ $? == 2 ]] || exit 1
  fi
  check_features
  check zdraw geometry dimensions
  check zdraw position stdscr position
  report "resized ${(j: :)dimensions} cached $position[5] $position[6]"
  barrier

  dimensions=(sentinel)
  check_features
  zdraw geometry dimensions
  report "zero $? ${(j: :)dimensions}"
  barrier

  # The terminal byte queued before the drawing/query/opt-in calls survives.
  # Ignore a resize event generated by the PTY dimension changes above.
  typeset key kkey
  typeset -i attempt
  check zdraw timeout sample 0
  for attempt in 1 2 3; do
    check zdraw input sample key kkey
    [[ $key == Z ]] && break
    [[ $kkey == RESIZE ]] || exit 1
  done
  [[ $key == Z ]] || exit 1
  report "input $key"

  # Standard parameter assignment must find a caller's local array.
  caller() {
    local -a local_size
    check zdraw geometry local_size
    report "local ${(j: :)local_size}"
  }
  caller
  ( typeset -ra frozen=(keep); zdraw geometry frozen ) 2>/dev/null
  report "readonly $?"
  zdraw geometry 2>/dev/null
  report "missing $?"
  zdraw geometry dimensions extra 2>/dev/null
  report "extra $?"
  check zdraw delwin sample
} always {
  zdraw end
}
check zdraw geometry dimensions
check_features
report "after ${(j: :)dimensions}"
