#!/usr/bin/env python3
"""Generate pinned Unicode 17 grapheme properties; normal builds need no network."""
import argparse
import hashlib
import json
from pathlib import Path
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('Other', 'CR', 'LF', 'Control', 'Extend', 'ZWJ', 'Regional_Indicator',
         'Prepend', 'SpacingMark', 'L', 'V', 'T', 'LV', 'LVT')


def generate(cache):
    manifest = json.loads((ROOT / 'tests/unicode/sources.json').read_text())
    props = bytearray(0x110000)
    for name in ('GraphemeBreakProperty.txt', 'emoji-data.txt', 'DerivedCoreProperties.txt'):
        path = cache / name
        record = manifest[name]
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(urllib.request.urlopen(record['url'], timeout=30).read())
        data = path.read_bytes()
        if hashlib.sha256(data).hexdigest() != record['sha256']:
            raise ValueError(f'Unicode source checksum mismatch: {name}')
        for line in data.decode().splitlines():
            fields = [f.strip() for f in line.split('#', 1)[0].split(';')]
            if len(fields) < 2:
                continue
            if name == 'GraphemeBreakProperty.txt':
                value = NAMES.index(fields[1])
            elif name == 'emoji-data.txt':
                if fields[1] != 'Extended_Pictographic':
                    continue
                value = 16
            else:
                if fields[1] != 'InCB':
                    continue
                value = {'Consonant': 32, 'Extend': 64, 'Linker': 96}[fields[2]]
            ends = fields[0].split('..')
            low, high = int(ends[0], 16), int(ends[-1], 16)
            for point in range(low, high + 1):
                props[point] |= value
    lines = ['/* Generated by scripts/generate-graphemes.py; Unicode 17.0.0.',
             ' * Derived from Unicode data, Copyright Unicode, Inc.',
             ' * SPDX-License-Identifier: Unicode-3.0',
             ' * The complete license is included below. Do not edit ranges manually.',
             ' */']
    license_text = (ROOT / 'tests/unicode/LICENSE.txt').read_text().strip()
    lines += ['/*\n' + '\n'.join((' * ' + line).rstrip() for line in license_text.splitlines()) + '\n */',
              '#define ZDRAW_GRAPHEME_VERSION "17.0.0"',
              'enum zdraw_gcb { ' + ', '.join('ZDG_' + n for n in NAMES) + ' };',
              'struct zdraw_grapheme_range { unsigned int first, last; unsigned char props; };',
              'static const struct zdraw_grapheme_range zdraw_grapheme_ranges[] = {']
    first = 0
    for end in range(1, len(props) + 1):
        if end == len(props) or props[end] != props[first]:
            if props[first]:
                lines.append('    {0x%x, 0x%x, %d},' % (first, end - 1, props[first]))
            first = end
    lines += ['};', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cache', type=Path, default=ROOT / '.build/unicode-17.0.0')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = generate(args.cache)
    target = ROOT / 'Src/Modules/zdraw_grapheme_data.h'
    if args.check:
        if target.read_text() != text:
            raise SystemExit('generated grapheme data differs')
    else:
        target.write_text(text)


if __name__ == '__main__':
    main()
